# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.network "forwarded_port", guest: 5000, host: 5000

    config.vm.provider "virtualbox" do |v|
        v.name = "devOpsAPI"
        v.memory = "1024"
        v.cpus = "2"
      end
    
    config.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "configureAPI.yml"
    end
    #config.vm.provision "shell", inline: <<-SHELL
    #    cd /vagrant
    #    sudo apt update && apt upgrade -y
    #    apt-get -y install python3-pip
    #    pip3 install -r requirements.txt
    #    gunicorn --conf gunicorn_conf.py --bind 0.0.0.0:5000 app:app

#    SHELL
end
